apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    version: v1
spec:
  containers:
    - name: myapp
      image:  apomic80/myapp:v1
      ports:
        - containerPort: 80